apiVersion: skaffold/v3     
kind: Config
build:
  artifacts:
  - image: ismailken/auth   
    context: auth
    sync:
      manual:
      - src: src/**/*.ts    
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}